# Generated by Django 3.1.7 on 2021-03-31 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_auto_20210331_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.FloatField(default=0.0, help_text='Calories', validators=[django.core.validators.MaxValueValidator(9999999)], verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(help_text='Name', max_length=255, verbose_name='Name'),
        ),
    ]
